spring.application.name=profile_service
spring.datasource.url=jdbc:postgresql://localhost:5432/rehaflow_db
spring.datasource.username=dequelite
spring.datasource.password=123

server.port=8081
spring.grpc.server.port=9091

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret.session=test_access_secret_123456
jwt.ttl.session=900000

jwt.secret.refresh=test_refresh_secret_654321
jwt.ttl.refresh=604800000
logging.level.root=DEBUG

grpc.search.host=localhost
grpc.search.port=9090